package agent

import "testing"

func TestFormatPromptText(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		input      string
		wantText   string
		wantSource PromptSource
	}{
		{
			name:       "plain text unchanged",
			input:      "explain this function",
			wantText:   "explain this function",
			wantSource: PromptSourceUser,
		},
		{
			name:       "bash input formatted as shell prompt",
			input:      "<bash-input>curl example.com</bash-input>",
			wantText:   "$ curl example.com",
			wantSource: PromptSourceBash,
		},
		{
			name:       "local command caveat stripped entirely",
			input:      `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>`,
			wantText:   "",
			wantSource: PromptSourceUser,
		},
		{
			name:       "bash stdout unwrapped",
			input:      "<bash-stdout>hello world</bash-stdout>",
			wantText:   "hello world",
			wantSource: PromptSourceBashOutput,
		},
		{
			name:       "bash stderr unwrapped",
			input:      "<bash-stderr>connection refused</bash-stderr>",
			wantText:   "connection refused",
			wantSource: PromptSourceBashOutput,
		},
		{
			name:       "empty bash output tags stripped",
			input:      "<bash-stdout></bash-stdout><bash-stderr></bash-stderr>",
			wantText:   "",
			wantSource: PromptSourceBashOutput,
		},
		{
			name:       "mixed stdout and stderr",
			input:      "<bash-stdout>ok</bash-stdout><bash-stderr>warning: something</bash-stderr>",
			wantText:   "okwarning: something",
			wantSource: PromptSourceBashOutput,
		},
		{
			name:       "slash command metadata stripped",
			input:      "<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args><local-command-stdout></local-command-stdout>",
			wantText:   "",
			wantSource: PromptSourceUser,
		},
		{
			name:       "real curl output cleaned up",
			input:      "<bash-stdout></bash-stdout><bash-stderr>% Total  % Received\ncurl: (7) Failed to connect</bash-stderr>",
			wantText:   "% Total  % Received\ncurl: (7) Failed to connect",
			wantSource: PromptSourceBashOutput,
		},
		{
			name:       "empty input",
			input:      "",
			wantText:   "",
			wantSource: PromptSourceUser,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := FormatPromptText(tc.input)
			if got.Text != tc.wantText {
				t.Errorf("FormatPromptText(%q).Text = %q, want %q", tc.input, got.Text, tc.wantText)
			}
			if got.Source != tc.wantSource {
				t.Errorf("FormatPromptText(%q).Source = %q, want %q", tc.input, got.Source, tc.wantSource)
			}
		})
	}
}

func TestTruncateString(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		input  string
		maxLen int
		want   string
	}{
		{name: "short string", input: "hello", maxLen: 10, want: "hello"},
		{name: "exact length", input: "hello", maxLen: 5, want: "hello"},
		{name: "truncated", input: "hello world", maxLen: 5, want: "hello…"},
		{name: "empty", input: "", maxLen: 5, want: ""},
		{name: "unicode safe", input: "日本語テスト", maxLen: 3, want: "日本語…"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := TruncateString(tc.input, tc.maxLen)
			if got != tc.want {
				t.Errorf("TruncateString(%q, %d) = %q, want %q", tc.input, tc.maxLen, got, tc.want)
			}
		})
	}
}
