package agent

import "testing"

func TestFormatPromptText(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "plain text unchanged",
			input: "explain this function",
			want:  "explain this function",
		},
		{
			name:  "bash input formatted as shell prompt",
			input: "<bash-input>curl example.com</bash-input>",
			want:  "$ curl example.com",
		},
		{
			name:  "local command caveat stripped entirely",
			input: `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>`,
			want:  "",
		},
		{
			name:  "bash stdout unwrapped",
			input: "<bash-stdout>hello world</bash-stdout>",
			want:  "hello world",
		},
		{
			name:  "bash stderr unwrapped",
			input: "<bash-stderr>connection refused</bash-stderr>",
			want:  "connection refused",
		},
		{
			name:  "empty bash output tags stripped",
			input: "<bash-stdout></bash-stdout><bash-stderr></bash-stderr>",
			want:  "",
		},
		{
			name:  "mixed stdout and stderr",
			input: "<bash-stdout>ok</bash-stdout><bash-stderr>warning: something</bash-stderr>",
			want:  "okwarning: something",
		},
		{
			name:  "slash command metadata stripped",
			input: "<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args><local-command-stdout></local-command-stdout>",
			want:  "",
		},
		{
			name:  "real curl output cleaned up",
			input: "<bash-stdout></bash-stdout><bash-stderr>% Total  % Received\ncurl: (7) Failed to connect</bash-stderr>",
			want:  "% Total  % Received\ncurl: (7) Failed to connect",
		},
		{
			name:  "empty input",
			input: "",
			want:  "",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := FormatPromptText(tc.input)
			if got != tc.want {
				t.Errorf("FormatPromptText(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestTruncateString(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		input  string
		maxLen int
		want   string
	}{
		{name: "short string", input: "hello", maxLen: 10, want: "hello"},
		{name: "exact length", input: "hello", maxLen: 5, want: "hello"},
		{name: "truncated", input: "hello world", maxLen: 5, want: "hello…"},
		{name: "empty", input: "", maxLen: 5, want: ""},
		{name: "unicode safe", input: "日本語テスト", maxLen: 3, want: "日本語…"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := TruncateString(tc.input, tc.maxLen)
			if got != tc.want {
				t.Errorf("TruncateString(%q, %d) = %q, want %q", tc.input, tc.maxLen, got, tc.want)
			}
		})
	}
}
